services:
#database 
  database:
    image: postgres:15
    container_name: amypay_database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: LesserKnown123
      POSTGRES_DB: amypay_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: amypay_backend
    build:
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - ./env 
    expose:
      - "9000"
    #include the networks 
    networks: 
      - amypay_network
    restart: unless-stopped
    cpus : "1"
    mem_limit: "512m"
  
volumes: 
  postgres_data:

networks:
  amypay_network:
    driver: bridge
