services:
#database 
  database:
    image: postgres:15
    container_name: amypay_database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: LesserKnown123
      POSTGRES_DB: amypay_db
    ports:
      - "5435:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - amypay_network

 #backend  
  backend:
    container_name: amypay_backend
    build:
      context: .
      dockerfile: backend/dockerfile
    env_file:
      - ./.env 
    expose:
      - "9000"
    depends_on:
      - database
    #include the networks 
    networks: 
      - amypay_network
    restart: unless-stopped
    cpus : "1"
    mem_limit: "512m"
  
volumes: 
  postgres_data:

networks:
  amypay_network:
    driver: bridge
