services:
  backend:
    build:
      context: .
      dockerfile: backend/dockerfile
    env_file:
      - backend/.env
    expose:
      - "9000"
    #include the networks 
    networks: 
      - amypay_network
    restart: unless-stopped

networks:
  amypay_network:
    driver: bridge
